ALTER TABLE customers
	ALTER COLUMN name TYPE VARCHAR (80),
	ALTER COLUMN address TYPE VARCHAR (80);

ALTER TABLE books
	ALTER COLUMN title TYPE VARCHAR (80),
	ALTER COLUMN category TYPE VARCHAR (80);
